### PR TITLE
Switch to functional tests with py.test

### PR DESCRIPTION
**Pull request by NDevox**
As promised 💥

### CODE REVIEW

**Comment by NDevox** [comment]
It's pretty much a like for like copy. There maybe could be some further adaptation to the py.test way of doing things, but this works pretty well.

**Comment by NDevox** [comment]
Travis failed to pull python 3.5 from google, so forcing a rebuild.

**Comment by evansd** [comment]
Looks awesome, thanks so much!

I'm going to take a bit of time to review before merging, not because I think there are any issues but I just want to make sure I understand how it's all working.

**Comment by NDevox** [comment]
I wouldn't expect anything less

**Pull request merged**
