### PR TITLE
Python 3.8 is now official, add it to the test matrix

### PR DESCRIPTION
**Pull request by Djailla**

### CODE REVIEW

**Comment by Djailla** [comment]
Hello @evansd any chance you take a look ? It's a pretty straight forward PR :)

**Comment by evansd** [comment]
Hi, thanks for this and the other PRs. I'm not convinced running the lint task under 3.8 is necessarily a good idea though. It's important for developer workflow that anyone contributing to WhiteNoise can run the lint tests locally and Python 3.8 isn't as widely available by default as Python 3.7 is. And I don't see any upside to running it under 3.8.

**Comment by Djailla** [comment]
@evansd agreed and changed

**Comment by Djailla** [comment]
@evansd up ?

**Pull request merged**
