### PR TITLE
Add the argparse dependency to whitenoise when installed on Python 2.6

### LINKED ISSUE #47: whitenoise is missing the argparse dependency when installed for Python 2.6
When you install whitenoise for Python 2.6:

    pip install whitenoise

It does not download the 'argparse' dependency automatically. Note that this library is included in the standard library for Python >= 2.7 and >= 3.2

If you try to use the whitenoise library without it (example from [Graphite](https://github.com/graphite-project/graphite-web)), you get:

    Traceback (most recent call last):
      File "/opt/graphite/conf/graphite.wsgi", line 32, in <module>
        from whitenoise.django import DjangoWhiteNoise
      File "/usr/lib/python2.6/site-packages/whitenoise/django.py", line 32, in <module>
        from .gzip import compress, extension_regex, GZIP_EXCLUDE_EXTENSIONS
      File "/usr/lib/python2.6/site-packages/whitenoise/gzip.py", line 4, in <module>
        import argparse
    ImportError: No module named argparse

### PR DESCRIPTION
**Pull request by movermeyer**
A patch to potentially fix #47.

### CODE REVIEW

**Comment by evansd** [comment]
Thanks. I think something like this will work, but the issue is making sure it plays nicely with wheel building. It looks like Zope had a similar issue [here](https://github.com/zopefoundation/ZODB/issues/36) but I haven't had a chance to digest that thread yet and work out if there's an applicable solution.

**Comment by luzfcb** [comment]
maybe something like this https://github.com/audreyr/cookiecutter/commit/c27bb76c6803ea66dfbdd6dd05b7679034ce54a3 would be better

```python
setup(
    name='whitenoise',
...
...
    extras_require={
        ':python_version=="2.6"': [
            'argparse>=1.4.0'
        ],
    },
...
```

but I'm not sure this works in Python 2.6

I am also feeling sorry for those who are obliged to use python 2.6. :pensive:

**Comment by movermeyer** [comment]
Right, I wasn't sure what was the appropriate way either. I ended up using the method used by [pyhocon](https://github.com/chimpler/pyhocon), so they might have an issue too.

**Comment by evansd** [comment]
Thanks @luzfcb, that looks like what I want.

There's obviously something amiss with the tests as they should have caught this earlier, so I need to look into that as well.

**Comment by evansd** [comment]
Fixed by 97f545c25a57975e2d62849df7b377ca712ce157 instead

**Comment by luzfcb** [comment]
:+1:

**Pull request closed without merging**
