### PR TITLE
Clean up intermediate files

### PR DESCRIPTION
**Pull request by evansd**

### CODE REVIEW

**Comment by evansd** [comment]
@edmorley Did you have any comments on this?

**Comment by edmorley** [comment]
Sorry for the delay, I'll try to take a look either today or tomorrow.

**Comment by edmorley** [comment]
Really sorry for not being able to get to this the last week - I'm now away until ~12th, but have made a note to look at it when I get back. Feel free to merge if needed before then and we can always always follow up after.

**Comment by edmorley** [comment]
I've set aside some time this coming weekend to look at this finally!

**Pull request merged**
