### PR TITLE
Test with GitHub Actions

### PR DESCRIPTION
**Pull request by adamchainz**
Use the same template as my other repos, downgraded to older Pythons.

### CODE REVIEW

**Comment by adamchainz** [comment]
Awaiting GitHub permissions to give this a spin.

**Review by evansd — APPROVED** [review]
Github Actions was already enabled, but I _think_ I need to approve your first PR and then it will allow you to run workflows.

**Comment by evansd** [comment]
It's possible you need to push again to trigger it.

**Comment by adamchainz** [comment]
I believe this won't run until merged. Possibly because I'm making the PR from a fork. I will make future PR's from the source repo, now I have access.

**Pull request merged**
