### PR TITLE
Handle FileNotFoundError and emit warning on broken symlink in scantree()

### LINKED ISSUE #605: FileNotFoundError during scantree() caused by broken symlink
### Python Version

3.9.18

### Django Version

4.1.13

### Package Version

6.7.0

### Description

A few days ago an unfortunate chain of events lead to a script producing a broken symlink in my `staticfiles` path, a subsequent automatic reload of the server caused whitenoise to update its file dict, ultimately leading to a `FileNotFoundError` in `scantree()` and crashing the whole thing.

I propose exception handling and a warning in https://github.com/evansd/whitenoise/pull/604

Not sure if there is a better way to test the broken symlink, other than committing one :thinking:

### PR DESCRIPTION
**Pull request by fdemmer**
Fixes #605.

### CODE REVIEW

**Comment by fdemmer** [comment]
Excellent work pre-commit! That is a indeed broken symlink... on purpose :)

**Comment by adamchainz** [comment]
Why would we turn this into a warning when it's a clear sign of something being misconfigured?

**Comment by fdemmer** [comment]
Wasn't sure about that either; silent exception handling would be just fine.

**Comment by adamchainz** [comment]
What I mean was, why do anything at all? A crash seems like a good thing. Broken symlinks seem like something that the user should track down and fix. Perhaps some static assets have gone missing.

**Comment by adamchainz** [comment]
Closing per the above. I'm not convinced Whitenoise should handle this edge case.

**Pull request closed without merging**
