### PR TITLE
Include warning in the documentation about middleware position

### PR DESCRIPTION
**Pull request by edevil**
Add a warning about the order of the configured middlewares.

### CODE REVIEW

**Comment by evansd** [comment]
Hi, thanks for this and sorry I'm only just getting to look at it now.

I need a bit more detail on the problem you were experiencing though, and ideally a reproducing example, before I can merge this because I'm not quite convinced by your explanation. WhiteNoise just acts as a standard piece of response-returning middleware, and doesn't do anything special or use any internal Django APIs. So if it is causing the issue you suggest then so will any other other piece of middleware that returns a response.

**Comment by edevil** [comment]
This is not specific to Whitenoise, see https://code.djangoproject.com/ticket/29069.

Django relies on the ```request_finished``` signal to release the DB connection, if one was requested during the processing of the request. When a request is served by Whitenoise this signal is not sent so if a previous middleware has made ORM requests the DB connection will not be closed. The same thing happens with the static and media file serving of Django itself, for example.

**Comment by evansd** [comment]
Ah, I see! Thanks

**Comment by evansd** [comment]
@edevil Can I just confirm: is this only a problem if you have other middleware that runs before WhiteNoise and opens a db connection? So if WhiteNoise is always the first bit of middleware this problem won't occur, is that right?

**Comment by edevil** [comment]
@evansd Yes, if WH is the first then it is not a problem. Or if those previous middlewares did not require a DB connection.

**Pull request closed without merging**
