### PR TITLE
Replace brotlipy with official Brotli package

### LINKED ISSUE #154: Recommend Brotli instead of brotlipy?
When Brotli support was first added to WhiteNoise, if I remember correctly, the official brotli repo did not yet have its own Python package/bindings. As such, the WhiteNoise docs recommend using [brotlipy](https://pypi.python.org/pypi/brotlipy).

However there's now the official Python package, [Brotli](https://pypi.python.org/pypi/Brotli), which I've been using with WhiteNoise for a while.

Unless there are good reasons to stick with the unofficial bindings, I think we should update the WhiteNoise docs to point people at the `Brotli` package instead.

### PR DESCRIPTION
**Pull request by keimlink**
Since the Brotli project offers an official Brotli Python package brotlipy can be replaced with Brotli. The official package is always up-to-date with the main Brotli project.

Brotli has been added as "brotli" to `extras_require` in `setup.py`. The installation instructions have been updated too. This allows users to install WhiteNoise together with Brotli and shows where the dependency is coming from.

To allow testing with a defined Brotli version a `constraints.txt` file has been added. (Local test setup and continuous integration configurations were already using Brotli instead of brotlipy.)

Fixes #154.

### CODE REVIEW

**Comment by evansd** [comment]
Thanks for this! Switching to the official Brotli package definitely looks like a good move. This PR brings in quite a few other changes as well though which I'll need time to review and understand before I can merge.

**Comment by keimlink** [comment]
I'm sorry for the huge amount of changes in a single pull request, Dave!

Initially I just wanted to add brotlipy to `extras_require` so that WhiteNoise and brotlipy can be installed together and it's clearer where the dependency comes from.

Then I discovered #154 and decided to replace brotlipy with Brotli.

The implementation itself was quickly done, but I also wanted to provide a clean testing setup. So I added `extras` to `tox.ini` and the `constraints.txt` file. The main idea was to reduce the number of places where the Brotli version is defined to keep the setup DRY. Also a library should not pin it's (optional) dependencies, so I didn't do this in `setup.py` and used pip's constraint feature.

Then I discovered that the test setup for Travis and AppVeyor was not using tox but repeated many steps. So I decided to convert both to tox.

Finally I ran into problems with Python 3.3 on Travis CI. Since Python 3.3 has passed it's end of life in September 2017 and the next WhiteNoise release will already contain breaking changes I made the decision to drop Python 3.3 support.

If you don't agree with any of the changes I made please let me know and I'll update the pull request.

**Comment by evansd** [comment]
Thanks so much for this. This was the first time I've come across pip's constraints files.

I think reducing the duplication between tox, travis and appveyor is definitely a good thing. I don't know if there's a more elegant way of handling the travis configuration so we can specify things as a matrix rather than listing every combination individually, but I'm happy to accept the PR as is and we can look into that later.

**Comment by evansd** [comment]
Oh also, I'd like to start testing on Python 3.7 but I haven't got round to setting that up yet and I hear it's not yet straightforward on Travis. If you have any experience with that and had time to do another PR that would be great :)

**Comment by evansd** [comment]
Managed to get Python 3.7 testing working myself:
https://github.com/evansd/whitenoise/commit/7bfa477868a9cdba83263b733c8e6f03c5608c71

**Pull request merged**
