### PR TITLE
Add basic support for HTTP 1.1 Range requests (RFC 7233)

### PR DESCRIPTION
**Pull request by bu2**
Add basic support for HTTP 1.1 Range requests (RFC 7233: https://tools.ietf.org/html/rfc7233).

Modify whitenoise.base.Whitenoise.serve() to handle Range requests.
The modification has been validated with Python 2.7 and Django 1.9 by streaming a "static" video file (MP4) to an iOS device (iPhone 6, iOS 9.3.1). Safari would refuse to play the video if it was not streamed to the device using Range requests and "Partial Content" responses.

### CODE REVIEW

**Comment by astagi** [comment]
Any update on this? @bu2 @evansd

**Comment by evansd** [comment]
@astagi It's on my todo list :) There haven't been a lot of people asking for this though, so it hasn't been a big priority for me. I guess most people serving video do it via a third party service anyway.

**Comment by rollcat** [comment]
`Range` header parsing could be a bit more robust. In `whitenoise/base.py` line 95:

> `a, b = environ['HTTP_RANGE'].split('=')[1].split('-')`
> `ValueError: too many values to unpack`

Value of `HTTP_RANGE` is:

>  `'bytes=0-10,113-123,226-236,339-349,452-462,565-575,678-688,791-801,904-914,1017-1027'`

The UA string (sadly [Sentry](sentry.io) clipped it :/):

> `Mozilla/5.0 (Linux; Android 6.0; XT1063 Build/MPB24.65-34-3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/54.0.2840.85...`

Perhaps it's too much to add a dependency on [Werkzeug](http://werkzeug.pocoo.org/), but their range parsing (`werkzeug.http.parse_range_header`) is quite robust and handles this case.

**Comment by evansd** [comment]
This has now been implemented.

**Pull request closed without merging**
